services:
  - type: web
    name: cardio-platform
    env: node
    plan: free
    buildCommand: |
      npm install
      cd frontend && npm install && npm run build && cd ..
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: ADMIN_PASSWORD
        sync: false
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
