services:
  - type: web
    name: cardio-platform
    env: node
    plan: free
    buildCommand: |
      npm install
      npm run build
    startCommand: node server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: ADMIN_PASSWORD
        sync: false
